version: '3'
services:
  frontend:
    build:
      context: ./ProfitAPI/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      - REACT_APP_API_URL=http://backend:5200

  backend:
    build:
      context: ./ProfitAPI/
      dockerfile: Dockerfile
    ports:
      - "5200:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
