version: '3'
services:
  frontend:
    build:
      context: ./ProfitAPI/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5200
    networks:
      - app-network

  backend:
    build:
      context: ./ProfitAPI/
      dockerfile: Dockerfile
    ports:
      - "5200:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=products;User=root;Password=example;
    command: ["dotnet", "ProfitAPI.dll"]
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge